[
  {
    "id": 0,
    "name": "INTERNAL_ERROR",
    "text": "Undefined internal error",
    "code": 500
  },
  {
    "id": 1,
    "name": "ER_DUP_ENTRY",
    "text": "Duplicate database entry"
  },
  {
    "id": 2,
    "name": "NO_SUCH_USER",
    "text": "Given user doesn't exist"
  },
  {
    "id": 3,
    "name": "INVALID_CREDENTIALS",
    "text": "Given credentials are invalid"
  },
  {
    "id": 4,
    "name": "ACC_DENIED",
    "text": "Access denied for this route",
    "code": 401
  },
  {
    "id": 5,
    "name": "INVALID_DATA",
    "text": "The provided data is invalid"
  },
  {
    "id": 6,
    "name": "NO_SUCH_OBJECT",
    "text": "No object found for the provided ID."
  },
  {
    "id": 7,
    "name": "UPDATE_FAILED",
    "text": "Update of the object failed."
  },
  {
    "id": 8,
    "name": "INVALID_PARAMETER",
    "text": "Invalid parameter provided"
  },
  {
    "id": 9,
    "name": "NO_SUCH_FIELD",
    "text": "Given field doesn't exist on the CRUD Model."
  },
  {
    "id": 10,
    "name": "NO_ID_PROVIDED",
    "text": "ID necessary for operation not provided."
  },
  {
    "id": 11,
    "name": "INVALID_LIST_FILTER",
    "text": "The provided list filter contained non-existent fields, values not matching the field type or requested partial matches for full match only types."
  },
  {
    "id": 12,
    "name": "ALREADY_DONE",
    "text": "The action you attempted to perform can only be done once and was already performed before."
  }
]
